=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/agent_to_building_levels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="agent_to_building_levels" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="agent_to_building_levels">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="agent building " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="agent_attributesagent_to_building_level" index-key="attribute " primary="no" unique="no" clustered="no"/>
<od:index index-name="agentsagent_to_building_level" index-key="agent " primary="no" unique="no" clustered="no"/>
<od:index index-name="building_levelsagent_to_building_level" index-key="building " primary="no" unique="no" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="agent" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="building" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="attribute" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="bonus" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/agent_to_building_levels.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="agent_to_building_levels.xsd" generated="2009-09-16T11:40:11">
<agent_to_building_levels>
<agent>middle_east_missionary</agent>
<building>enlightened_university</building>
<attribute>zeal</attribute>
<bonus>1</bonus>
<s_ColLineage>kNOq8QMAAACQ06rxBgAAAJDTqvEEAAAAkNOq8QUAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{35A659BB-50BF-46BB-931C-C2AC6191B64F}</s_GUID>
<s_Lineage>kNOq8QcAAAAAAAAAAAAAAA==
</s_Lineage>
</agent_to_building_levels>
<agent_to_building_levels>
<agent>middle_east_missionary</agent>
<building>royal_academy</building>
<attribute>zeal</attribute>
<bonus>1</bonus>
<s_ColLineage>kNOq8QMAAACQ06rxAQAAAJDTqvEEAAAAkNOq8QUAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{48B8D18D-FDAD-4195-95AC-5FEA130831E1}</s_GUID>
<s_Lineage>kNOq8QYAAAAAAAAAAAAAAA==
</s_Lineage>
</agent_to_building_levels>
<agent_to_building_levels>
<agent>middle_east_missionary</agent>
<building>royal_observatory</building>
<attribute>zeal</attribute>
<bonus>1</bonus>
<s_ColLineage>kNOq8QMAAACQ06rxAQAAAJDTqvEEAAAAkNOq8QUAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FE98F826-C2CB-4C1F-AB4E-76B8ADF458A9}</s_GUID>
<s_Lineage>kNOq8QYAAAAAAAAAAAAAAA==
</s_Lineage>
</agent_to_building_levels>
<agent_to_building_levels>
<agent>middle_east_missionary</agent>
<building>university</building>
<attribute>zeal</attribute>
<bonus>1</bonus>
<s_ColLineage>kNOq8QMAAACQ06rxBgAAAJDTqvEEAAAAkNOq8QUAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{314C1048-7AD9-48A0-9DD1-E24DADC71FE5}</s_GUID>
<s_Lineage>kNOq8QcAAAAAAAAAAAAAAA==
</s_Lineage>
</agent_to_building_levels>
</dataroot>
