=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/battlefield_buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="battlefield_buildings" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="battlefield_buildings">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="key " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="battlefield_building_categoriesbattlefield_buildings" index-key="category " primary="no" unique="no" clustered="no"/>
<od:index index-name="battlefield_building_transformationsbattlefield_buildings" index-key="transformation " primary="no" unique="no" clustered="no"/>
<od:index index-name="battlefield_buildings_namesbattlefield_buildings" index-key="onscreen_name " primary="no" unique="no" clustered="no"/>
<od:index index-name="models_buildingbattlefield_buildings" index-key="model " primary="no" unique="no" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="key" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="category" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="model" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="audio_material" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="hit_points" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="gun_type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="onscreen_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="transformation" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/battlefield_buildings.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="battlefield_buildings.xsd" generated="2009-05-20T14:13:00">
<battlefield_buildings>
<key>american_bridge_basic</key>
<category>bridge</category>
<model>american_bridge_basic</model>
<audio_material>wood</audio_material>
<hit_points>150</hit_points>
<s_ColLineage>kNOq8QIAAAA0CceOCgAAADQJx44KAAAANAnHjgoAAAA0CceOCgAAAJDTqvEBAAAA
kNOq8QEAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{651E6E0A-AB4A-48A2-9D27-226D5085EB39}</s_GUID>
<s_Lineage>NAnHjgoAAACQ06rxCQAAAAAAAAAAAAAA
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_bridge_refined</key>
<category>bridge</category>
<model>american_bridge_refined</model>
<audio_material>wood</audio_material>
<hit_points>250</hit_points>
<s_ColLineage>kNOq8QIAAAA0CceOCQAAADQJx44JAAAANAnHjgkAAAA0CceOCQAAAJDTqvEBAAAA
kNOq8QEAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{BF3E421F-9A79-4456-8082-A5ADD0B3813D}</s_GUID>
<s_Lineage>NAnHjgkAAACQ06rxCAAAAAAAAAAAAAAA
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_church</key>
<category>church</category>
<model>american_church</model>
<audio_material>wood</audio_material>
<hit_points>500</hit_points>
<s_ColLineage>kNOq8QIAAACQ06rxAwAAAJDTqvEDAAAAkNOq8QMAAACQ06rxAwAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAQAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{07397D87-E8A0-4570-BFE3-BCAD55B070DA}</s_GUID>
<s_Lineage>kNOq8QMAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_fence</key>
<category>house</category>
<model>american_fence</model>
<audio_material>wood</audio_material>
<hit_points>15</hit_points>
<transformation>terrain_shear</transformation>
<s_ColLineage>kNOq8QIAAACQ06rxBwAAAJDTqvEHAAAAkNOq8QcAAACQ06rxBwAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAwAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{EE7A37F9-739F-4311-A47F-3BC794093758}</s_GUID>
<s_Lineage>kNOq8QcAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_fenceend</key>
<category>house</category>
<model>american_fenceend</model>
<audio_material>wood</audio_material>
<hit_points>15</hit_points>
<transformation>terrain_shear</transformation>
<s_ColLineage>kNOq8QIAAACQ06rxBwAAAJDTqvEHAAAAkNOq8QcAAACQ06rxBwAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAwAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{ADCFFB94-2C40-4640-BC87-59777EB44D98}</s_GUID>
<s_Lineage>kNOq8QcAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_gaet</key>
<category>house</category>
<model>american_gaet</model>
<audio_material>wood</audio_material>
<hit_points>15</hit_points>
<transformation>terrain_shear</transformation>
<s_ColLineage>kNOq8QIAAACQ06rxBwAAAJDTqvEHAAAAkNOq8QcAAACQ06rxBwAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAwAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{12B350DF-2C24-477E-9C53-CF0706330DF0}</s_GUID>
<s_Lineage>kNOq8QcAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house01</key>
<category>house</category>
<model>american_house01</model>
<audio_material>wood</audio_material>
<hit_points>200</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxDwAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{20B92E33-0475-4E03-A9F8-6E2A59E491C1}</s_GUID>
<s_Lineage>kNOq8Q8AAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house01b</key>
<category>house</category>
<model>american_house01b</model>
<audio_material>wood</audio_material>
<hit_points>200</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxDwAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{400B5F4A-FA19-48D6-BFFA-F02F2BE7EC7A}</s_GUID>
<s_Lineage>kNOq8Q8AAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house02</key>
<category>house</category>
<model>american_house02</model>
<audio_material>wood</audio_material>
<hit_points>200</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxDwAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{81C20EC4-4A45-4A4E-824D-5AE7FF705FD3}</s_GUID>
<s_Lineage>kNOq8Q8AAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house02b</key>
<category>house</category>
<model>american_house02b</model>
<audio_material>wood</audio_material>
<hit_points>200</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxDwAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{EBAD8498-D6DD-4A08-A5C2-775B67153EA6}</s_GUID>
<s_Lineage>kNOq8Q8AAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house03</key>
<category>house</category>
<model>american_house03</model>
<audio_material>wood</audio_material>
<hit_points>200</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxDwAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{D6AC1E6E-1CF1-4CA3-98FA-8F0044ECEAA9}</s_GUID>
<s_Lineage>kNOq8Q8AAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house03b</key>
<category>house</category>
<model>american_house03b</model>
<audio_material>wood</audio_material>
<hit_points>200</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxDwAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{64A2B66D-9F6B-4E1A-81CB-BA901023F10A}</s_GUID>
<s_Lineage>kNOq8Q8AAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house04</key>
<category>house</category>
<model>american_house04</model>
<audio_material>wood</audio_material>
<hit_points>150</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxEAAAAJDTqvEQAAAAkNOq8RAAAACQ06rxEAAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{F89906E1-8BCE-4D1C-938E-8CDD7A0F2845}</s_GUID>
<s_Lineage>kNOq8RAAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house04b</key>
<category>house</category>
<model>american_house04b</model>
<audio_material>wood</audio_material>
<hit_points>150</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxEAAAAJDTqvEQAAAAkNOq8RAAAACQ06rxEAAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{00E029A7-B622-442C-B624-DC880598F9A8}</s_GUID>
<s_Lineage>kNOq8RAAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house05</key>
<category>house</category>
<model>american_house05</model>
<audio_material>brick</audio_material>
<hit_points>300</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q8AAACQ06rxEQAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{70DA3085-C458-43F1-8114-6646276E79A4}</s_GUID>
<s_Lineage>kNOq8REAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house05b</key>
<category>house</category>
<model>american_house05b</model>
<audio_material>brick</audio_material>
<hit_points>300</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q8AAACQ06rxEQAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{2887AFE7-E766-47B1-AB41-EB013176F26B}</s_GUID>
<s_Lineage>kNOq8REAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house06</key>
<category>house</category>
<model>american_house06</model>
<audio_material>wood</audio_material>
<hit_points>300</hit_points>
<onscreen_name>House</onscreen_name>
<s_ColLineage>kNOq8QIAAACQ06rxDgAAAJDTqvEOAAAAkNOq8Q4AAACQ06rxEAAAAJDTqvEBAAAA
kNOq8QcAAAAAAAAAAAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{9591030A-777D-4C9D-AA5C-910A86B0892D}</s_GUID>
<s_Lineage>kNOq8RAAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_house06b</key>
<category>house</category>
<model>american_house06b</model>
<audio_material>wood</audio_material>
<hit_points>300</hit_points>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAAkNOq8QIAAACQ06rxBAAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAQAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{121E3CB6-4CE6-4805-84D4-81FF45DD8478}</s_GUID>
<s_Lineage>kNOq8QQAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_monument</key>
<category>incidental</category>
<model>american_monument</model>
<audio_material>stone</audio_material>
<hit_points>100</hit_points>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAAkNOq8QIAAACQ06rxAgAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAQAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{71E0B32B-27B1-4DB6-9D3E-28CE2D053828}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</battlefield_buildings>
<battlefield_buildings>
<key>american_ruin01</key>
<category>ruins</category>
<model>american_ruin01</model>
<audio_material>stone</audio_material>
<hit_points>500</hit_points>
<s_ColLineage>kNOq8QcAAACQ06rxCAAAAJDTqvEIAAAAkNOq8QgAAACQ06rxCAAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAQAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{B2FE55CE-F6E3-4376-AD1C-DF92FFAE76EC}</s_GUID>
<s_Lineage>kNOq8QgAAAAAAAAAAAAAAA==
</s_Lineage>
