=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/building_levels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="building_levels" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="building_levels">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="level_name " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="building_chainsbuilding_levels" index-key="chain " primary="no" unique="no" clustered="no"/>
<od:index index-name="commoditiesbuilding_levels" index-key="commodity " primary="no" unique="no" clustered="no"/>
<od:index index-name="gov_type_key" index-key="gov_type_key " primary="no" unique="no" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="level_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="chain" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="condition" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="only_in_capital" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="create_time" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="create_cost" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="upkeep_cost" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="demolition_cost" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="zoc" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="lower_happiness" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="upper_happiness" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="repression" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="gdp" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="town_wealth_growth" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="pop_change" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="maxpop_change" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="commodity" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="commodity_vol" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="building_category" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="gov_type_key" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="military_prestige" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="naval_prestige" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="economic_prestige" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="enlightenment_prestige" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Gen_condition" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/building_levels.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="building_levels.xsd" generated="2010-06-01T16:32:24">
<building_levels>
<level_name>fFort1_wooden_artillery_fort</level_name>
<chain>fFort</chain>
<level>0</level>
<only_in_capital>0</only_in_capital>
<create_time>3</create_time>
<create_cost>4000</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>0</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>1</Gen_condition>
<s_ColLineage>W4e7tREAAABbh7u1EgAAAJDTqvEKAAAAkNOq8QEAAABquW1qFgAAAGq5bWoUAAAA
kNOq8QEAAACQ06rxAQAAAJDTqvEBAAAAkNOq8QEAAACQ06rxAQAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAwAAAJDTqvEDAAAAkNOq8QMAAACQ06rxAwAAAJDTqvEDAAAA
kNOq8QMAAACQ06rxAwAAAAAAAAAAAAAAAAAAAAAAAABquW1qFQAAAJDTqvEIAAAA
kNOq8QgAAACQ06rxCAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{42D86B8F-5586-4199-9B27-8302364DD1B4}</s_GUID>
<s_Lineage>arltahYAAABbh7u1EgAAAJDTqvEMAAAAAAAAAAAAAAA=
</s_Lineage>
</building_levels>
<building_levels>
<level_name>fFort2_western_artillery_fort</level_name>
<chain>fFort</chain>
<level>1</level>
<only_in_capital>0</only_in_capital>
<create_time>6</create_time>
<create_cost>8000</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>10</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>1</Gen_condition>
<s_ColLineage>W4e7tRMAAABbh7u1FAAAAJDTqvEMAAAAkNOq8QEAAABquW1qGQAAAGq5bWoWAAAA
kNOq8QEAAACQ06rxAQAAAJDTqvEBAAAAkNOq8QEAAACQ06rxAQAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAwAAAJDTqvEDAAAAkNOq8QMAAACQ06rxAwAAAJDTqvEDAAAA
kNOq8QMAAACQ06rxAwAAAAAAAAAAAAAAAAAAAAAAAABquW1qFwAAAJDTqvEIAAAA
kNOq8QgAAACQ06rxCAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{E10BF130-5755-40C5-8965-F17C696A4893}</s_GUID>
<s_Lineage>arltahkAAABbh7u1FAAAAJDTqvEOAAAAAAAAAAAAAAA=
</s_Lineage>
</building_levels>
<building_levels>
<level_name>fFort3_star_fort</level_name>
<chain>fFort</chain>
<level>2</level>
<only_in_capital>0</only_in_capital>
<create_time>12</create_time>
<create_cost>16000</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>20</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>1</Gen_condition>
<s_ColLineage>W4e7tRUAAABbh7u1FgAAAFuHu7UUAAAAkNOq8QEAAABquW1qGwAAAGq5bWoZAAAA
kNOq8QEAAACQ06rxAQAAAJDTqvEBAAAAkNOq8QEAAACQ06rxAQAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAwAAAJDTqvEDAAAAkNOq8QMAAACQ06rxAwAAAJDTqvEDAAAA
kNOq8QMAAACQ06rxAwAAAAAAAAAAAAAAAAAAAAAAAABquW1qGgAAAJDTqvEIAAAA
kNOq8QgAAACQ06rxCAAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{C82741B3-1E89-488D-87AB-85C930FA6A15}</s_GUID>
<s_Lineage>arltahsAAABbh7u1FgAAAJDTqvEPAAAAAAAAAAAAAAA=
</s_Lineage>
</building_levels>
<building_levels>
<level_name>pNavy1_shipyard</level_name>
<chain>pNavy</chain>
<level>0</level>
<only_in_capital>0</only_in_capital>
<create_time>4</create_time>
<create_cost>1200</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>0</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>0</Gen_condition>
<s_ColLineage>W4e7tQUAAABbh7u1AwAAAFuHu7UGAAAAW4e7tQIAAABbh7u1CgAAAFuHu7UOAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAGq5bWoQAAAA
W4e7tQIAAABbh7u1AgAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{A743BC60-79D9-4378-AA51-3D3A14B19CE4}</s_GUID>
<s_Lineage>arltahAAAABbh7u1DgAAAAAAAAAAAAAA
</s_Lineage>
</building_levels>
<building_levels>
<level_name>pNavy2_dockyard</level_name>
<chain>pNavy</chain>
<level>1</level>
<only_in_capital>0</only_in_capital>
<create_time>8</create_time>
<create_cost>3600</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>0</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>0</Gen_condition>
<s_ColLineage>W4e7tQUAAABbh7u1AwAAAFuHu7UGAAAAW4e7tQIAAABbh7u1CgAAAFuHu7UNAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAGq5bWoPAAAA
W4e7tQIAAABbh7u1AgAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{290D597D-D16F-4D78-A232-CF5985D18687}</s_GUID>
<s_Lineage>arltag8AAABbh7u1DQAAAAAAAAAAAAAA
</s_Lineage>
</building_levels>
<building_levels>
<level_name>pNavy3_steam_drydock</level_name>
<chain>pNavy</chain>
<level>2</level>
<only_in_capital>0</only_in_capital>
<create_time>12</create_time>
<create_cost>10800</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>0</military_prestige>
<naval_prestige>20</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>0</Gen_condition>
<s_ColLineage>W4e7tQQAAABbh7u1AwAAAFuHu7UFAAAAW4e7tQIAAABbh7u1CgAAAFuHu7UPAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAGq5bWoSAAAA
W4e7tQIAAABbh7u1AgAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{4B1296D2-49C1-4D2E-ADF7-C7FDCCFB3F81}</s_GUID>
<s_Lineage>arltahIAAABbh7u1DwAAAAAAAAAAAAAA
</s_Lineage>
</building_levels>
<building_levels>
<level_name>pNavyTutorial1_shipyard</level_name>
<chain>pNavyTutorial</chain>
<level>0</level>
<only_in_capital>0</only_in_capital>
<create_time>1</create_time>
<create_cost>1250</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>0</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<s_ColLineage>W4e7tQMAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQEAAABbh7u1AQAAAFuHu7UBAAAA
W4e7tQEAAABbh7u1AQAAAFuHu7UBAAAAW4e7tQEAAABbh7u1AQAAAFuHu7UBAAAA
W4e7tQEAAABbh7u1AQAAAFuHu7UBAAAAW4e7tQEAAABbh7u1AQAAAGq5bWoFAAAA
W4e7tQEAAABbh7u1AQAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{DED03AA9-C5BE-4227-8C5F-F9133303A3F8}</s_GUID>
<s_Lineage>arltagUAAABbh7u1AwAAAAAAAAAAAAAA
</s_Lineage>
</building_levels>
<building_levels>
<level_name>pTrade1_trading_port</level_name>
<chain>pTrade</chain>
<level>0</level>
<only_in_capital>0</only_in_capital>
<create_time>4</create_time>
<create_cost>1200</create_cost>
<upkeep_cost>0</upkeep_cost>
<demolition_cost>0</demolition_cost>
<zoc>0</zoc>
<lower_happiness>0</lower_happiness>
<upper_happiness>0</upper_happiness>
<repression>0</repression>
<gdp>0</gdp>
<town_wealth_growth>0</town_wealth_growth>
<pop_change>0</pop_change>
<maxpop_change>0</maxpop_change>
<commodity_vol>0</commodity_vol>
<military_prestige>0</military_prestige>
<naval_prestige>0</naval_prestige>
<economic_prestige>0</economic_prestige>
<enlightenment_prestige>0</enlightenment_prestige>
<Gen_condition>0</Gen_condition>
<s_ColLineage>W4e7tQQAAABbh7u1AwAAAFuHu7UCAAAAW4e7tQIAAABbh7u1CAAAAFuHu7UNAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
arltag8AAABbh7u1AgAAAA==
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FE447732-E025-4C5B-A122-29E3938BD962}</s_GUID>
<s_Lineage>arltag8AAABbh7u1DQAAAAAAAAAAAAAA
</s_Lineage>
</building_levels>
<building_levels>
<level_name>pTrade2_commercial_port</level_name>
