=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/campaign_map_towns_and_ports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="campaign_map_towns_and_ports" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="campaign_map_towns_and_ports">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="town_id " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="regionscampaign_map_towns_and_ports" index-key="region " primary="no" unique="no" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
<od:index index-name="slotscampaign_map_towns_and_ports" index-key="slot_type " primary="no" unique="no" clustered="no"/>
<od:index index-name="town_id" index-key="town_id " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="town_id" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="region" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="slot_type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="onscreen_name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="project_specific" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/campaign_map_towns_and_ports.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="campaign_map_towns_and_ports.xsd" generated="2010-04-16T14:51:34">
<campaign_map_towns_and_ports>
<town_id>town:eur_aquitaine:mont_de_marsan</town_id>
<region>eur_aquitaine</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Mont-de-Marsan</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{B3A29665-E66A-48D5-BD98-AC17F52E7CFB}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_austria:graz</town_id>
<region>eur_austria</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Graz</onscreen_name>
<template>nap_eur_town_edu</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{B955EA53-F850-477A-B4CF-9EA0FC7FDED5}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_austria:linz</town_id>
<region>eur_austria</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Linz</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{98CFBCF5-D2B9-4A0E-BC57-9EFDB1231D8C}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_austria:salzburg</town_id>
<region>eur_austria</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Salzburg</onscreen_name>
<template>nap_eur_town_ind</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAGq5bWoGAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{A81D808A-39C9-4520-B5BE-B0D531CBF683}</s_GUID>
<s_Lineage>arltagYAAABbh7u1BQAAALGarOsCAAAAAAAAAAAAAAA=
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_baden_wurttemberg:heidelberg</town_id>
<region>eur_baden_wurttemberg</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Heidelberg</onscreen_name>
<template>nap_eur_town_edu</template>
<s_ColLineage>sZqs6wQAAACxmqzrAwAAAFuHu7UFAAAAsZqs6wIAAABbh7u1BwAAAFuHu7UGAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{50229076-3742-4BE9-A02D-290A4605FE8E}</s_GUID>
<s_Lineage>W4e7tQcAAACxmqzrBAAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_balkans:sarajevo</town_id>
<region>eur_balkans</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Sarajevo</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UEAAAAsZqs6wIAAABbh7u1BgAAAFuHu7UFAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{22025BF7-F7EE-4117-A5E6-DCEA3625EFE4}</s_GUID>
<s_Lineage>W4e7tQYAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_bavaria:augsburg</town_id>
<region>eur_bavaria</region>
<slot_type>town-industrial</slot_type>
<onscreen_name>Augsburg</onscreen_name>
<template>nap_eur_town_ind</template>
<s_ColLineage>arltagIAAABquW1qAgAAAGq5bWoCAAAAarltagIAAABquW1qAgAAAGq5bWoBAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{548EFE64-628F-47C4-830F-D087A332C208}</s_GUID>
<s_Lineage>arltagIAAAAAAAAAAAAAAA==
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_bavaria:regensburg</town_id>
<region>eur_bavaria</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Regensburg</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAGq5bWoGAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{50D7AF68-4FC9-4B1F-93D3-A5F6F07C5DBA}</s_GUID>
<s_Lineage>arltagYAAABbh7u1BQAAALGarOsCAAAAAAAAAAAAAAA=
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_belarus:vitebsk</town_id>
<region>eur_belarus</region>
<slot_type>town-industrial</slot_type>
<onscreen_name>Vitebsk</onscreen_name>
<template>nap_eur_town_ind</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{CD6DE0C9-4A3D-4B89-91BE-FAD502306D56}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_belgorod_guberniya:bryansk</town_id>
<region>eur_belgorod_guberniya</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Bryansk</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wYAAACxmqzrBQAAAFuHu7UHAAAAsZqs6wIAAABbh7u1CQAAAFuHu7UIAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FE029649-9931-4CC8-AEDF-56D9D0A9F7D0}</s_GUID>
<s_Lineage>W4e7tQkAAACxmqzrBgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_bohemia:budweis</town_id>
<region>eur_bohemia</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Budweis</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wMAAACxmqzrAgAAAFuHu7UEAAAAsZqs6wIAAABbh7u1BgAAAFuHu7UFAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{93735055-5DC7-4F1E-8256-969FC3ABEB02}</s_GUID>
<s_Lineage>W4e7tQYAAACxmqzrAwAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_brandenburg:kustrin</town_id>
<region>eur_brandenburg</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Küstrin</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{8F098B4C-502E-41E6-9262-5C47EDB9930A}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_brandenburg:magdeburg</town_id>
<region>eur_brandenburg</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Magdeburg</onscreen_name>
<template>nap_eur_town_edu</template>
<s_ColLineage>sZqs6wUAAACxmqzrAgAAAFuHu7UGAAAAsZqs6wUAAABbh7u1CAAAAFuHu7UHAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{7338D02C-755D-49FB-995F-9194CA1F953D}</s_GUID>
<s_Lineage>W4e7tQgAAACxmqzrBQAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_brandenburg:potsdam</town_id>
<region>eur_brandenburg</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Potsdam</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wUAAACxmqzrAgAAAFuHu7UGAAAAsZqs6wUAAABbh7u1CAAAAFuHu7UHAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{76A762DB-8F33-48D2-ADA3-FDFE529974F3}</s_GUID>
<s_Lineage>W4e7tQgAAACxmqzrBQAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_catalonia:cervera</town_id>
<region>eur_catalonia</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Cervera</onscreen_name>
<template>nap_eur_town_edu</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{49AF5669-11F9-4EB8-B9DA-0DC9ACF47673}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_cleves_mark:munster</town_id>
<region>eur_cleves_mark</region>
<slot_type>town-industrial</slot_type>
<onscreen_name>Münster</onscreen_name>
<template>nap_eur_town_ind</template>
<s_ColLineage>sZqs6wMAAACxmqzrAgAAAFuHu7UEAAAAsZqs6wIAAABbh7u1BgAAAFuHu7UFAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{55E20E1C-6BB3-4406-AA4E-E9FEDF23ECFC}</s_GUID>
<s_Lineage>W4e7tQYAAACxmqzrAwAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_courland:kuldiga</town_id>
<region>eur_courland</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Kuldīga</onscreen_name>
<template>nap_eur_town_edu</template>
<s_ColLineage>sZqs6wMAAACxmqzrAgAAAFuHu7UEAAAAsZqs6wMAAABbh7u1BgAAAFuHu7UFAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{6A368DA7-A158-4DBA-BE6B-56448C5B2355}</s_GUID>
<s_Lineage>W4e7tQYAAACxmqzrAwAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_croatia:rijeka</town_id>
<region>eur_croatia</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Rijeka</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>sZqs6wIAAACxmqzrAgAAAFuHu7UDAAAAsZqs6wIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{C28846CA-5F4D-45CA-BEF9-1E1368E63D2D}</s_GUID>
<s_Lineage>W4e7tQUAAACxmqzrAgAAAAAAAAAAAAAA
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_denmark:hamburg</town_id>
<region>eur_denmark</region>
<slot_type>town-commercial</slot_type>
<onscreen_name>Hamburg</onscreen_name>
<template>nap_eur_town_com</template>
<s_ColLineage>W4e7tQMAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1BQAAAFuHu7UEAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{A0830FA9-EABB-4CCF-9E13-F49CF9E87314}</s_GUID>
<s_Lineage>W4e7tQUAAAAAAAAAAAAAAA==
</s_Lineage>
</campaign_map_towns_and_ports>
<campaign_map_towns_and_ports>
<town_id>town:eur_denmark:schleswig</town_id>
<region>eur_denmark</region>
<slot_type>town-intellectual</slot_type>
<onscreen_name>Schleswig</onscreen_name>
<template>nap_eur_town_edu</template>
