=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/disasters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="disasters" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="disasters">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="key " primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="key" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="frequency" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="season" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="one_year_warning" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="linked_to_object" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="climate_restriction" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="minimum_scale" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="maximum_scale" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/disasters.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="disasters.xsd" generated="2007-05-04T14:26:03">
<disasters>
<key>dustbowl</key>
<frequency>0</frequency>
<season>both</season>
<one_year_warning>0</one_year_warning>
<linked_to_object>n</linked_to_object>
<climate_restriction>hot_dry</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
<disasters>
<key>earthquake</key>
<frequency>20</frequency>
<season>both</season>
<one_year_warning>0</one_year_warning>
<linked_to_object>n</linked_to_object>
<climate_restriction>n</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
<disasters>
<key>flood</key>
<frequency>10</frequency>
<season>summer</season>
<one_year_warning>0</one_year_warning>
<linked_to_object>rivers</linked_to_object>
<climate_restriction>n</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
<disasters>
<key>hurricane</key>
<frequency>10</frequency>
<season>summer</season>
<one_year_warning>0</one_year_warning>
<linked_to_object>n</linked_to_object>
<climate_restriction>tropical</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
<disasters>
<key>locusts</key>
<frequency>0</frequency>
<season>both</season>
<one_year_warning>0</one_year_warning>
<linked_to_object>n</linked_to_object>
<climate_restriction>hot_dry</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
<disasters>
<key>storm</key>
<frequency>4</frequency>
<season>both</season>
<one_year_warning>0</one_year_warning>
<linked_to_object>n</linked_to_object>
<climate_restriction>n</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
<disasters>
<key>volcano</key>
<frequency>50</frequency>
<season>both</season>
<one_year_warning>1</one_year_warning>
<linked_to_object>volcano</linked_to_object>
<climate_restriction>n</climate_restriction>
<minimum_scale>2</minimum_scale>
<maximum_scale>5</maximum_scale>
</disasters>
</dataroot>
