=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/effect_bonus_value_commodity_junction.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="effect_bonus_value_commodity_junction" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="effect_bonus_value_commodity_junction">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="effect bonus_value_id commodity " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="bonus_value_id" index-key="bonus_value_id " primary="no" unique="no" clustered="no"/>
<od:index index-name="campaign_bonus_value_ids_commeffect_bonus_value_commodity_jun" index-key="bonus_value_id " primary="no" unique="no" clustered="no"/>
<od:index index-name="commoditieseffect_bonus_value_commodity_junction" index-key="commodity " primary="no" unique="no" clustered="no"/>
<od:index index-name="effectseffect_bonus_value_commodity_junction" index-key="effect " primary="no" unique="no" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="effect" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="bonus_value_id" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="commodity" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="project_specific" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/effect_bonus_value_commodity_junction.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="effect_bonus_value_commodity_junction.xsd" generated="2010-03-11T17:31:20">
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_coffee</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_coffee</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{C8F9E727-6173-4AC2-B996-2D12E5011B68}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_cotton</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_cotton</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{52A0E76F-06F7-4198-99C3-7800C4369927}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_furs</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_furs</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{8171E5D6-ED3B-4102-83EB-5A193CA632BC}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_spices</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_spices</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{45594A4D-B2A1-4C42-BB6B-3134E5228B8D}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_sugar</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_sugar</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{C5709BF9-A419-460F-AD16-4761706AD9F5}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_tea</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_tea</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{D825F4EF-59DD-41F7-80C8-1C9126F2814B}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
<effect_bonus_value_commodity_junction>
<effect>commodity_prod_tobacco</effect>
<bonus_value_id>production</bonus_value_id>
<commodity>res_tobacco</commodity>
<s_ColLineage>kNOq8QIAAACQ06rxAgAAAJDTqvECAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FA969520-FAFE-4243-9AF7-106338466D1C}</s_GUID>
<s_Lineage>kNOq8QIAAAAAAAAAAAAAAA==
</s_Lineage>
</effect_bonus_value_commodity_junction>
</dataroot>
