=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/unit_stats_naval_experience_bonuses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="unit_stats_naval_experience_bonuses" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="unit_stats_naval_experience_bonuses">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="xp_level " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="xp_level" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="melee_defence" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="core_gunner_loading_skill" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="core_gunner_marksmanship" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="morale" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="mp_fixed_cost" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="mp_experience_cost_multiplier" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/unit_stats_naval_experience_bonuses.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="unit_stats_naval_experience_bonuses.xsd" generated="2009-01-29T19:23:25">
<unit_stats_naval_experience_bonuses>
<xp_level>0</xp_level>
<melee_defence>0</melee_defence>
<core_gunner_loading_skill>0</core_gunner_loading_skill>
<core_gunner_marksmanship>0</core_gunner_marksmanship>
<morale>0</morale>
<mp_fixed_cost>0</mp_fixed_cost>
<mp_experience_cost_multiplier>1</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxAQAAAJDTqvEBAAAAkNOq8QEAAACQ06rxAQAAAJDTqvEGAAAA
kNOq8QYAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{67384D2E-3900-4558-9A76-94451698F63A}</s_GUID>
<s_Lineage>kNOq8QYAAAAAAAAAAAAAAA==
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>1</xp_level>
<melee_defence>1</melee_defence>
<core_gunner_loading_skill>5</core_gunner_loading_skill>
<core_gunner_marksmanship>2</core_gunner_marksmanship>
<morale>1</morale>
<mp_fixed_cost>10</mp_fixed_cost>
<mp_experience_cost_multiplier>1.05</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBgAAAJDTqvEKAAAAkNOq8QcAAACQ06rxAQAAAJDTqvELAAAA
kNOq8QwAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{525B7411-B770-4681-9C4C-CD5A1B33EACC}</s_GUID>
<s_Lineage>kNOq8QwAAAAAAAAAAAAAAA==
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>2</xp_level>
<melee_defence>2</melee_defence>
<core_gunner_loading_skill>10</core_gunner_loading_skill>
<core_gunner_marksmanship>4</core_gunner_marksmanship>
<morale>1</morale>
<mp_fixed_cost>20</mp_fixed_cost>
<mp_experience_cost_multiplier>1.075</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBgAAAJDTqvEKAAAAkNOq8QcAAACQ06rxAQAAAJDTqvELAAAA
kNOq8QwAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{AC711B1D-268F-4224-B7E7-FED90E487FFD}</s_GUID>
<s_Lineage>kNOq8QwAAAAAAAAAAAAAAA==
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>3</xp_level>
<melee_defence>3</melee_defence>
<core_gunner_loading_skill>10</core_gunner_loading_skill>
<core_gunner_marksmanship>6</core_gunner_marksmanship>
<morale>2</morale>
<mp_fixed_cost>40</mp_fixed_cost>
<mp_experience_cost_multiplier>1.1</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44MAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QsAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{D1580EF0-0133-49B4-9873-76842573DCCA}</s_GUID>
<s_Lineage>NAnHjgwAAACQ06rxCwAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>4</xp_level>
<melee_defence>4</melee_defence>
<core_gunner_loading_skill>15</core_gunner_loading_skill>
<core_gunner_marksmanship>8</core_gunner_marksmanship>
<morale>2</morale>
<mp_fixed_cost>60</mp_fixed_cost>
<mp_experience_cost_multiplier>1.125</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44NAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QsAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{7FD191BB-D237-496C-8A60-7FFD31AA1372}</s_GUID>
<s_Lineage>NAnHjg0AAACQ06rxCwAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>5</xp_level>
<melee_defence>5</melee_defence>
<core_gunner_loading_skill>15</core_gunner_loading_skill>
<core_gunner_marksmanship>10</core_gunner_marksmanship>
<morale>3</morale>
<mp_fixed_cost>90</mp_fixed_cost>
<mp_experience_cost_multiplier>1.15</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44MAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QsAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{96E0B5AB-D73B-42DC-95ED-ABD6AAC89628}</s_GUID>
<s_Lineage>NAnHjgwAAACQ06rxCwAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>6</xp_level>
<melee_defence>6</melee_defence>
<core_gunner_loading_skill>20</core_gunner_loading_skill>
<core_gunner_marksmanship>12</core_gunner_marksmanship>
<morale>3</morale>
<mp_fixed_cost>125</mp_fixed_cost>
<mp_experience_cost_multiplier>1.175</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44MAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QsAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{6746681F-F53E-4562-8671-618D5543E7AD}</s_GUID>
<s_Lineage>NAnHjgwAAACQ06rxCwAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>7</xp_level>
<melee_defence>7</melee_defence>
<core_gunner_loading_skill>20</core_gunner_loading_skill>
<core_gunner_marksmanship>14</core_gunner_marksmanship>
<morale>4</morale>
<mp_fixed_cost>160</mp_fixed_cost>
<mp_experience_cost_multiplier>1.2</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44MAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QsAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{72733A25-C0E7-4A19-8325-E5424BAB8AEE}</s_GUID>
<s_Lineage>NAnHjgwAAACQ06rxCwAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>8</xp_level>
<melee_defence>8</melee_defence>
<core_gunner_loading_skill>25</core_gunner_loading_skill>
<core_gunner_marksmanship>16</core_gunner_marksmanship>
<morale>4</morale>
<mp_fixed_cost>205</mp_fixed_cost>
<mp_experience_cost_multiplier>1.225</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44NAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QwAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{4EB95DCC-978D-40C0-AB52-9984582FB978}</s_GUID>
<s_Lineage>NAnHjg0AAACQ06rxDAAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
<unit_stats_naval_experience_bonuses>
<xp_level>9</xp_level>
<melee_defence>9</melee_defence>
<core_gunner_loading_skill>25</core_gunner_loading_skill>
<core_gunner_marksmanship>18</core_gunner_marksmanship>
<morale>5</morale>
<mp_fixed_cost>255</mp_fixed_cost>
<mp_experience_cost_multiplier>1.25</mp_experience_cost_multiplier>
<s_ColLineage>kNOq8QEAAACQ06rxBQAAADQJx44MAAAAkNOq8QYAAACQ06rxAQAAAJDTqvEKAAAA
kNOq8QsAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{5825C03D-D144-41F9-AE5F-CCCC1A066D03}</s_GUID>
<s_Lineage>NAnHjgwAAACQ06rxCwAAAAAAAAAAAAAA
</s_Lineage>
</unit_stats_naval_experience_bonuses>
</dataroot>
