=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/unit_stats_naval_crew.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="unit_stats_naval_crew" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="unit_stats_naval_crew">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="unit_type " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="s_GUID" index-key="s_GUID " primary="no" unique="yes" clustered="no"/>
<od:index index-name="battle_animations_tableunit_stats_naval_crew" index-key="man_animations_table " primary="no" unique="no" clustered="no"/>
<od:index index-name="battle_entitiesunit_stats_naval_crew" index-key="battle_entity " primary="no" unique="no" clustered="no"/>
<od:index index-name="key" index-key="unit_type " primary="no" unique="no" clustered="no"/>
<od:index index-name="s_Generation" index-key="s_Generation " primary="no" unique="no" clustered="no"/>
<od:index index-name="warscape_animatedunit_stats_naval_crew" index-key="soldier_model " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="unit_type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="core_loading_skill" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="core_marksmanship" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="melee_attack" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="melee_defence" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="melee_weapon_type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="pistols" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="ammo" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="battle_entity" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="soldier_model" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="man_animations_table" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="equipment_theme" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="armour_audio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="armour" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="spacing" minOccurs="0" od:jetType="single" od:sqlSType="real" type="xsd:float"/>
<xsd:element name="discipline" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/unit_stats_naval_crew.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="unit_stats_naval_crew.xsd" generated="2010-03-18T15:34:18">
<unit_stats_naval_crew>
<unit_type>euro_guncrew</unit_type>
<core_loading_skill>5</core_loading_skill>
<core_marksmanship>40</core_marksmanship>
<melee_attack>4</melee_attack>
<melee_defence>3</melee_defence>
<melee_weapon_type>pike</melee_weapon_type>
<pistols>0</pistols>
<ammo>0</ammo>
<battle_entity>infantry_euro_light</battle_entity>
<soldier_model>euro_naval_gunner</soldier_model>
<man_animations_table>man_naval_cannon_crew</man_animations_table>
<equipment_theme>generic_naval_gunner</equipment_theme>
<armour_audio>ph</armour_audio>
<armour>1</armour>
<spacing>1.5</spacing>
<discipline>3</discipline>
<s_ColLineage>kNOq8QEAAACQ06rxAQAAAJDTqvEBAAAANAnHjgkAAAA0CceOCQAAAJDTqvEBAAAA
kNOq8QEAAACQ06rxAQAAAFuHu7ULAAAANAnHjgoAAACQ06rxAQAAAJDTqvEIAAAA
kNOq8QEAAACQ06rxAQAAAFuHu7UNAAAAkNOq8QYAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FA94BFA7-F765-4EC5-B8C7-58044FFB42C3}</s_GUID>
<s_Lineage>W4e7tQ0AAAA0CceOCgAAAJDTqvEIAAAAAAAAAAAAAAA=
</s_Lineage>
</unit_stats_naval_crew>
<unit_stats_naval_crew>
<unit_type>euro_marine</unit_type>
<core_loading_skill>35</core_loading_skill>
<core_marksmanship>45</core_marksmanship>
<melee_attack>13</melee_attack>
<melee_defence>7</melee_defence>
<melee_weapon_type>bayonet</melee_weapon_type>
<pistols>1</pistols>
<ammo>18</ammo>
<battle_entity>infantry_euro_medium</battle_entity>
<soldier_model>euro_marines</soldier_model>
<man_animations_table>man_musket</man_animations_table>
<equipment_theme>generic_naval_marine</equipment_theme>
<armour_audio>ph</armour_audio>
<armour>3</armour>
<spacing>1.2</spacing>
<discipline>5</discipline>
<s_ColLineage>kNOq8QEAAABbh7u1DAAAAJDTqvEBAAAANAnHjgkAAAA0CceOCAAAAJDTqvEBAAAA
NAnHjgoAAACQ06rxAQAAAFuHu7ULAAAAkNOq8QEAAACQ06rxAQAAAJDTqvEHAAAA
kNOq8QEAAACQ06rxAQAAAFuHu7UOAAAAkNOq8QUAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{51AB003C-7409-403A-AEEF-A779F756E7B9}</s_GUID>
<s_Lineage>W4e7tQ4AAAA0CceOCgAAAJDTqvEHAAAAAAAAAAAAAAA=
</s_Lineage>
</unit_stats_naval_crew>
<unit_stats_naval_crew>
<unit_type>euro_seaman</unit_type>
<core_loading_skill>5</core_loading_skill>
<core_marksmanship>40</core_marksmanship>
<melee_attack>4</melee_attack>
<melee_defence>3</melee_defence>
<melee_weapon_type>cutlass</melee_weapon_type>
<pistols>0</pistols>
<ammo>0</ammo>
<battle_entity>infantry_euro_light</battle_entity>
<soldier_model>euro_able_seamen</soldier_model>
<man_animations_table>man_seaman</man_animations_table>
<equipment_theme>generic_naval_seaman</equipment_theme>
<armour_audio>ph</armour_audio>
<armour>1</armour>
<spacing>1.5</spacing>
<discipline>3</discipline>
<s_ColLineage>kNOq8QEAAACQ06rxAQAAAJDTqvEBAAAANAnHjgcAAAA0CceOBwAAAJDTqvEBAAAA
NAnHjggAAACQ06rxAQAAAFuHu7UJAAAAkNOq8QEAAACQ06rxAQAAAJDTqvEGAAAA
kNOq8QEAAACQ06rxAQAAAFuHu7UKAAAAkNOq8QUAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{78ED88EA-6DA9-436A-AF0E-E60BDB98E8DE}</s_GUID>
<s_Lineage>W4e7tQoAAAA0CceOCAAAAJDTqvEGAAAAAAAAAAAAAAA=
</s_Lineage>
</unit_stats_naval_crew>
<unit_stats_naval_crew>
<unit_type>ottoman_guncrew</unit_type>
<core_loading_skill>5</core_loading_skill>
<core_marksmanship>40</core_marksmanship>
<melee_attack>4</melee_attack>
<melee_defence>3</melee_defence>
<melee_weapon_type>pike</melee_weapon_type>
<pistols>0</pistols>
<ammo>0</ammo>
<battle_entity>infantry_euro_light</battle_entity>
<soldier_model>barbary_pirates</soldier_model>
<man_animations_table>man_naval_cannon_crew</man_animations_table>
<equipment_theme>generic_naval_gunner</equipment_theme>
<armour_audio>ph</armour_audio>
<armour>1</armour>
<spacing>1.5</spacing>
<discipline>3</discipline>
<s_ColLineage>W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQMAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{DE7864CB-0EAA-4AD9-AE4B-7A7A344B4ADD}</s_GUID>
<s_Lineage>W4e7tQMAAAAAAAAAAAAAAA==
</s_Lineage>
</unit_stats_naval_crew>
<unit_stats_naval_crew>
<unit_type>ottoman_marine</unit_type>
<core_loading_skill>35</core_loading_skill>
<core_marksmanship>45</core_marksmanship>
<melee_attack>13</melee_attack>
<melee_defence>7</melee_defence>
<melee_weapon_type>bayonet</melee_weapon_type>
<pistols>1</pistols>
<ammo>18</ammo>
<battle_entity>infantry_euro_medium</battle_entity>
<soldier_model>barbary_pirates</soldier_model>
<man_animations_table>man_musket</man_animations_table>
<equipment_theme>generic_naval_marine</equipment_theme>
<armour_audio>ph</armour_audio>
<armour>3</armour>
<spacing>1.2</spacing>
<discipline>5</discipline>
<s_ColLineage>W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQMAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{6F8DEDDD-2D60-4E38-8D09-58CEBAC32E2B}</s_GUID>
<s_Lineage>W4e7tQMAAAAAAAAAAAAAAA==
</s_Lineage>
</unit_stats_naval_crew>
<unit_stats_naval_crew>
<unit_type>ottoman_seaman</unit_type>
<core_loading_skill>5</core_loading_skill>
<core_marksmanship>40</core_marksmanship>
<melee_attack>4</melee_attack>
<melee_defence>3</melee_defence>
<melee_weapon_type>cutlass</melee_weapon_type>
<pistols>0</pistols>
<ammo>0</ammo>
<battle_entity>infantry_euro_light</battle_entity>
<soldier_model>barbary_pirates</soldier_model>
<man_animations_table>man_seaman</man_animations_table>
<equipment_theme>generic_naval_seaman</equipment_theme>
<armour_audio>ph</armour_audio>
<armour>1</armour>
<spacing>1.5</spacing>
<discipline>3</discipline>
<s_ColLineage>W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQMAAABbh7u1AgAAAFuHu7UCAAAA
W4e7tQIAAABbh7u1AgAAAFuHu7UCAAAAW4e7tQIAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{5D8E4264-8BC5-419E-AC82-C6E0B26A3C4C}</s_GUID>
<s_Lineage>W4e7tQMAAAAAAAAAAAAAAA==
</s_Lineage>
</unit_stats_naval_crew>
</dataroot>
