=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/agent_abilities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="agent_abilities" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="agent_abilities">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ability agent " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="abilitiesagent_abilities" index-key="ability " primary="no" unique="no" clustered="no"/>
<od:index index-name="agentsagent_abilities" index-key="agent " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ability" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="agent" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="default_value" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/agent_abilities.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="agent_abilities.xsd" generated="2007-01-29T16:55:54">
<agent_abilities>
<ability>command_land</ability>
<agent>admiral</agent>
<default_value>4</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_land</ability>
<agent>bandit</agent>
<default_value>2</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_land</ability>
<agent>captain</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_land</ability>
<agent>colonel</agent>
<default_value>3</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_land</ability>
<agent>explorer</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_land</ability>
<agent>general</agent>
<default_value>5</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_land</ability>
<agent>pirate</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_sea</ability>
<agent>admiral</agent>
<default_value>5</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_sea</ability>
<agent>captain</agent>
<default_value>3</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_sea</ability>
<agent>general</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>command_sea</ability>
<agent>pirate</agent>
<default_value>2</default_value>
</agent_abilities>
<agent_abilities>
<ability>convert</ability>
<agent>missionary</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>research</ability>
<agent>thinker</agent>
<default_value>2</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>bandit</agent>
<default_value>2</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>explorer</agent>
<default_value>2</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>missionary</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>pirate</agent>
<default_value>2</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>settler</agent>
<default_value>1</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>spy</agent>
<default_value>4</default_value>
</agent_abilities>
<agent_abilities>
<ability>subterfuge</ability>
<agent>thinker</agent>
<default_value>1</default_value>
</agent_abilities>
</dataroot>
