=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/battle_cities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="battle_cities" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="battle_cities">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="city" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="minimum_building_scale" minOccurs="1" od:jetType="decimal" od:sqlSType="decimal" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:decimal">
<xsd:totalDigits value="18"/>
<xsd:fractionDigits value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="maximum_building_scale" minOccurs="1" od:jetType="decimal" od:sqlSType="decimal" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:decimal">
<xsd:totalDigits value="18"/>
<xsd:fractionDigits value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="town_min_distance" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="city_min_distance" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="town_radius" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="city_radius" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="number_of_town_buildings" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="number_of_city_buildings" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/battle_cities.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="battle_cities.xsd" generated="2009-07-13T15:08:52">
<battle_cities>
<city>American</city>
<minimum_building_scale>0.75</minimum_building_scale>
<maximum_building_scale>1.25</maximum_building_scale>
<town_min_distance>2100</town_min_distance>
<city_min_distance>3000</city_min_distance>
<town_radius>500</town_radius>
<city_radius>1000</city_radius>
<number_of_town_buildings>400</number_of_town_buildings>
<number_of_city_buildings>900</number_of_city_buildings>
<s_ColLineage>NAnHjgIAAAA0CceOAQAAADQJx44DAAAANAnHjgMAAAA0CceOAwAAADQJx44GAAAA
NAnHjgMAAAA0CceOCgAAADQJx44IAAAANAnHjgkAAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{0F30A6A8-9594-481F-9E11-D9C5C99BB1CC}</s_GUID>
<s_Lineage>NAnHjgoAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_cities>
<battle_cities>
<city>Eastern</city>
<minimum_building_scale>0.75</minimum_building_scale>
<maximum_building_scale>1.25</maximum_building_scale>
<town_min_distance>2100</town_min_distance>
<city_min_distance>3000</city_min_distance>
<town_radius>500</town_radius>
<city_radius>1000</city_radius>
<number_of_town_buildings>400</number_of_town_buildings>
<number_of_city_buildings>900</number_of_city_buildings>
<s_ColLineage>NAnHjgIAAAA0CceOAQAAADQJx44DAAAANAnHjgQAAAA0CceOBQAAADQJx44LAAAA
NAnHjgcAAAA0CceODwAAADQJx44NAAAANAnHjg4AAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{AAACD1AE-8AF1-4B5B-A4B4-39C19EF4B87F}</s_GUID>
<s_Lineage>NAnHjg8AAAAAAAAAAAAAAA==
</s_Lineage>
</battle_cities>
<battle_cities>
<city>European</city>
<minimum_building_scale>0.75</minimum_building_scale>
<maximum_building_scale>1.25</maximum_building_scale>
<town_min_distance>2100</town_min_distance>
<city_min_distance>3000</city_min_distance>
<town_radius>500</town_radius>
<city_radius>1000</city_radius>
<number_of_town_buildings>400</number_of_town_buildings>
<number_of_city_buildings>900</number_of_city_buildings>
<s_ColLineage>NAnHjgIAAAA0CceOAgAAADQJx44DAAAANAnHjgQAAAA0CceOBQAAADQJx44LAAAA
NAnHjgcAAAA0CceODwAAADQJx44NAAAANAnHjg4AAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{90FBFA7E-0D86-4ECE-9337-B55E79EFB624}</s_GUID>
<s_Lineage>NAnHjg8AAAAAAAAAAAAAAA==
</s_Lineage>
</battle_cities>
<battle_cities>
<city>Native</city>
<minimum_building_scale>0.75</minimum_building_scale>
<maximum_building_scale>0.9</maximum_building_scale>
<town_min_distance>2000</town_min_distance>
<city_min_distance>2000</city_min_distance>
<town_radius>600</town_radius>
<city_radius>600</city_radius>
<number_of_town_buildings>15</number_of_town_buildings>
<number_of_city_buildings>15</number_of_city_buildings>
<s_ColLineage>NAnHjgIAAAA0CceOAQAAADQJx44RAAAANAnHjhEAAAA0CceOCwAAADQJx44LAAAA
NAnHjg0AAAA0CceODAAAADQJx44PAAAANAnHjg8AAAA=
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{4C90716E-DE37-4679-B459-9FB080397EB8}</s_GUID>
<s_Lineage>NAnHjhEAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_cities>
</dataroot>
