=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/battle_entities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="battle_entities" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="battle_entities">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="key" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="class_validation" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="walk_speed" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="run_speed" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="acceleration" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="deceleration" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="charge_speed" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="crawl_speed" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="charge_distance_commence_run" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="charge_distance_adopt_charge_pose" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="charge_distance_pick_target" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="radius" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="shape" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="radii_ratio" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="mass" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="height" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="fire_arc_close" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="fire_arc_loose" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="turn_speed" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="hit_points" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/battle_entities.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="battle_entities.xsd" generated="2010-04-15T09:21:15">
<battle_entities>
<key>ammo_caisson_large</key>
<class_validation>artillery</class_validation>
<type>ammo_caisson</type>
<walk_speed>1.4</walk_speed>
<run_speed>3.42</run_speed>
<acceleration>2</acceleration>
<deceleration>2</deceleration>
<charge_speed>5.22</charge_speed>
<crawl_speed>1</crawl_speed>
<charge_distance_commence_run>20</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>20</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>20</charge_distance_pick_target>
<radius>2</radius>
<shape>ellipse</shape>
<radii_ratio>0.25</radii_ratio>
<mass>900</mass>
<height>2.5</height>
<fire_arc_close>30</fire_arc_close>
<fire_arc_loose>45</fire_arc_loose>
<turn_speed>45</turn_speed>
<hit_points>50</hit_points>
<s_ColLineage>W4e7tQwAAABbh7u1DAAAAGq5bWoVAAAAW4e7tQwAAABbh7u1DAAAAFuHu7UMAAAA
W4e7tQwAAABbh7u1DAAAAFuHu7UMAAAAW4e7tQwAAABbh7u1DAAAAFuHu7UMAAAA
W4e7tQwAAABbh7u1DAAAAFuHu7UMAAAAW4e7tQwAAABbh7u1DAAAAFuHu7UMAAAA
W4e7tQwAAABbh7u1DAAAAGq5bWoSAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FED5BE43-3D80-4604-A4C5-258D6585BC45}</s_GUID>
<s_Lineage>arltahUAAABbh7u1DQAAADQJx44KAAAAkNOq8QkAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_entities>
<battle_entities>
<key>ammo_caisson_small</key>
<class_validation>artillery</class_validation>
<type>ammo_caisson</type>
<walk_speed>1.55</walk_speed>
<run_speed>3.6</run_speed>
<acceleration>2</acceleration>
<deceleration>2</deceleration>
<charge_speed>5.85</charge_speed>
<crawl_speed>1</crawl_speed>
<charge_distance_commence_run>20</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>20</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>20</charge_distance_pick_target>
<radius>2</radius>
<shape>ellipse</shape>
<radii_ratio>0.25</radii_ratio>
<mass>700</mass>
<height>2.3</height>
<fire_arc_close>30</fire_arc_close>
<fire_arc_loose>45</fire_arc_loose>
<turn_speed>45</turn_speed>
<hit_points>50</hit_points>
<s_ColLineage>W4e7tQwAAABbh7u1DAAAAGq5bWoUAAAAW4e7tQwAAABbh7u1DAAAAFuHu7UMAAAA
W4e7tQwAAABbh7u1DAAAAFuHu7UMAAAAW4e7tQwAAABbh7u1DAAAAFuHu7UMAAAA
W4e7tQwAAABbh7u1DAAAAFuHu7UMAAAAW4e7tQwAAABbh7u1DAAAAFuHu7UMAAAA
W4e7tQwAAABbh7u1DAAAAGq5bWoSAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{69D89E12-6390-4317-9259-2A9C72F22C11}</s_GUID>
<s_Lineage>arltahQAAABbh7u1DQAAADQJx44KAAAAkNOq8QkAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_entities>
<battle_entities>
<key>artillery_fixed</key>
<class_validation>artillery</class_validation>
<type>artillery</type>
<walk_speed>0</walk_speed>
<run_speed>0</run_speed>
<acceleration>2</acceleration>
<deceleration>4</deceleration>
<charge_speed>0</charge_speed>
<crawl_speed>0</crawl_speed>
<charge_distance_commence_run>0</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>0</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>0</charge_distance_pick_target>
<radius>1.5</radius>
<shape>ellipse</shape>
<radii_ratio>0.5</radii_ratio>
<mass>2000</mass>
<height>1.5</height>
<fire_arc_close>360</fire_arc_close>
<fire_arc_loose>360</fire_arc_loose>
<turn_speed>45</turn_speed>
<hit_points>25</hit_points>
<s_ColLineage>W4e7tRQAAABbh7u1FAAAAFuHu7UUAAAAW4e7tRQAAABbh7u1FAAAAFuHu7UUAAAA
W4e7tRQAAABbh7u1FAAAAFuHu7UUAAAAW4e7tRQAAABbh7u1FAAAAFuHu7UUAAAA
W4e7tRQAAABbh7u1FAAAAFuHu7UUAAAAW4e7tRQAAABquW1qHwAAAGq5bWogAAAA
W4e7tRQAAABbh7u1FAAAAGq5bWocAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{8A24D5F5-C95C-4016-AE8C-5C3DC44E5E21}</s_GUID>
<s_Lineage>arltaiAAAABbh7u1FQAAADQJx44SAAAAkNOq8RAAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_entities>
<battle_entities>
<key>artillery_light</key>
<class_validation>artillery</class_validation>
<type>artillery</type>
<walk_speed>0.9</walk_speed>
<run_speed>1.8</run_speed>
<acceleration>2</acceleration>
<deceleration>4</deceleration>
<charge_speed>1.8</charge_speed>
<crawl_speed>1</crawl_speed>
<charge_distance_commence_run>30</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>20</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>10</charge_distance_pick_target>
<radius>1.5</radius>
<shape>ellipse</shape>
<radii_ratio>0.5</radii_ratio>
<mass>1000</mass>
<height>1.2</height>
<fire_arc_close>140</fire_arc_close>
<fire_arc_loose>140</fire_arc_loose>
<turn_speed>45</turn_speed>
<hit_points>25</hit_points>
<s_ColLineage>W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAAW4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAA
W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAAW4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAA
W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAAW4e7tQ0AAABquW1qGgAAAGq5bWobAAAA
W4e7tQ0AAABbh7u1DQAAAGq5bWoUAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{3B8E8006-F196-4270-A76D-14703C541C7D}</s_GUID>
<s_Lineage>arltahsAAABbh7u1DgAAADQJx44LAAAAkNOq8QkAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_entities>
<battle_entities>
<key>artillery_medium</key>
<class_validation>artillery</class_validation>
<type>artillery</type>
<walk_speed>0.63</walk_speed>
<run_speed>1.35</run_speed>
<acceleration>2</acceleration>
<deceleration>4</deceleration>
<charge_speed>1.35</charge_speed>
<crawl_speed>0.7</crawl_speed>
<charge_distance_commence_run>30</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>20</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>10</charge_distance_pick_target>
<radius>1.5</radius>
<shape>ellipse</shape>
<radii_ratio>0.5</radii_ratio>
<mass>1500</mass>
<height>1.3</height>
<fire_arc_close>140</fire_arc_close>
<fire_arc_loose>140</fire_arc_loose>
<turn_speed>45</turn_speed>
<hit_points>25</hit_points>
<s_ColLineage>W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAAW4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAA
W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAAW4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAA
W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAAW4e7tQ4AAABquW1qHAAAAGq5bWodAAAA
W4e7tQ4AAABbh7u1DgAAAGq5bWoVAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{168A9C3B-269F-44CB-AB59-ECCCB310AD59}</s_GUID>
<s_Lineage>arltah0AAABbh7u1DwAAADQJx44MAAAAkNOq8QoAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_entities>
<battle_entities>
<key>artillery_siege</key>
<class_validation>artillery</class_validation>
<type>artillery</type>
<walk_speed>0.36</walk_speed>
<run_speed>0.9</run_speed>
<acceleration>2</acceleration>
<deceleration>4</deceleration>
<charge_speed>0.9</charge_speed>
<crawl_speed>0.4</crawl_speed>
<charge_distance_commence_run>30</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>20</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>10</charge_distance_pick_target>
<radius>1.5</radius>
<shape>ellipse</shape>
<radii_ratio>0.5</radii_ratio>
<mass>2000</mass>
<height>1.5</height>
<fire_arc_close>140</fire_arc_close>
<fire_arc_loose>140</fire_arc_loose>
<turn_speed>45</turn_speed>
<hit_points>25</hit_points>
<s_ColLineage>W4e7tQsAAABbh7u1CwAAAFuHu7ULAAAAW4e7tQsAAABbh7u1CwAAAFuHu7ULAAAA
W4e7tQsAAABbh7u1CwAAAFuHu7ULAAAAW4e7tQsAAABbh7u1CwAAAFuHu7ULAAAA
W4e7tQsAAABbh7u1CwAAAFuHu7ULAAAAW4e7tQsAAABquW1qFgAAAGq5bWoWAAAA
W4e7tQsAAABbh7u1CwAAAGq5bWoSAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{FCD37F7E-13E6-48F0-A22E-32E3C1C094CF}</s_GUID>
<s_Lineage>arltahYAAABbh7u1DAAAADQJx44JAAAAkNOq8QcAAAAAAAAAAAAAAA==
</s_Lineage>
</battle_entities>
<battle_entities>
<key>camel</key>
<class_validation>cavalry</class_validation>
<type>camel</type>
<walk_speed>2.16</walk_speed>
<run_speed>6.3</run_speed>
<acceleration>2</acceleration>
<deceleration>6</deceleration>
<charge_speed>8.1</charge_speed>
<crawl_speed>2</crawl_speed>
<charge_distance_commence_run>40</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>30</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>25</charge_distance_pick_target>
<radius>2</radius>
<shape>ellipse</shape>
<radii_ratio>0.25</radii_ratio>
<mass>600</mass>
<height>2.5</height>
<fire_arc_close>90</fire_arc_close>
<fire_arc_loose>90</fire_arc_loose>
<turn_speed>90</turn_speed>
<hit_points>1</hit_points>
<s_ColLineage>W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAAW4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAA
W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAAW4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAA
W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAAW4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAA
W4e7tQ4AAABbh7u1DgAAAFuHu7UOAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{84624E57-AA87-449E-ADB8-02A2C5D72828}</s_GUID>
<s_Lineage>W4e7tQ4AAAA0CceODQAAAJDTqvELAAAAAAAAAAAAAAA=
</s_Lineage>
</battle_entities>
<battle_entities>
<key>elephant</key>
<class_validation>cavalry</class_validation>
<type>elephant</type>
<walk_speed>1.8</walk_speed>
<run_speed>4.5</run_speed>
<acceleration>2</acceleration>
<deceleration>4</deceleration>
<charge_speed>6.3</charge_speed>
<crawl_speed>2</crawl_speed>
<charge_distance_commence_run>40</charge_distance_commence_run>
<charge_distance_adopt_charge_pose>30</charge_distance_adopt_charge_pose>
<charge_distance_pick_target>25</charge_distance_pick_target>
<radius>2</radius>
<shape>ellipse</shape>
<radii_ratio>0.5</radii_ratio>
<mass>5000</mass>
<height>3.5</height>
<fire_arc_close>30</fire_arc_close>
<fire_arc_loose>45</fire_arc_loose>
<turn_speed>90</turn_speed>
<hit_points>3</hit_points>
<s_ColLineage>W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAAW4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAA
W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAAW4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAA
W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAAW4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAA
W4e7tQ0AAABbh7u1DQAAAFuHu7UNAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{1F6E0494-6D89-4009-BB2C-5A9915DEFB82}</s_GUID>
<s_Lineage>W4e7tQ0AAAA0CceODAAAAJDTqvELAAAAAAAAAAAAAAA=
</s_Lineage>
</battle_entities>
<battle_entities>
<key>gun_train_2_horse</key>
<class_validation>artillery</class_validation>
<type>gun_train_2</type>
<walk_speed>1.4</walk_speed>
<run_speed>1.8</run_speed>
<acceleration>2</acceleration>
<deceleration>2</deceleration>
<charge_speed>5.85</charge_speed>
<crawl_speed>1</crawl_speed>
