=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/models_unit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="models_unit" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="models_unit">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="key " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="key" index-key="key " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="key" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/models_unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="models_unit.xsd" generated="2007-02-15T10:10:48">
<models_unit>
<key>euro_guard_infantry</key>
</models_unit>
<models_unit>
<key>guard_infantry</key>
</models_unit>
<models_unit>
<key>gun_crew_2</key>
</models_unit>
<models_unit>
<key>line_infantry_2</key>
</models_unit>
<models_unit>
<key>model_british_middle_line_infantry</key>
</models_unit>
<models_unit>
<key>officer_artillery_2</key>
</models_unit>
<models_unit>
<key>officer_guard</key>
</models_unit>
<models_unit>
<key>officer_horse_light_1</key>
</models_unit>
<models_unit>
<key>officer_line_infantry_2</key>
</models_unit>
</dataroot>
