=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/projectiles_explosions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="projectiles_explosions" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="projectiles_explosions">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="key" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="detonator_type" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="detonation_type" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="detonation_radius" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="detonation_duration" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="detonation_speed" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="detonation_damage" minOccurs="1" od:jetType="single" od:sqlSType="real" od:nonNullable="yes" type="xsd:float"/>
<xsd:element name="particle_type" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="particle_number" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="explosion_particle_effect" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="distance_from_target" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="error_margin" minOccurs="1" od:jetType="double" od:sqlSType="float" od:nonNullable="yes" type="xsd:double"/>
<xsd:element name="non_lethal_detonation" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="explosion_particle_effect_on_ground" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/empire/projectiles_explosions.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="projectiles_explosions.xsd" generated="2009-08-10T12:33:27">
<projectiles_explosions>
<key>carcass_12lb</key>
<detonator_type>fuse</detonator_type>
<detonation_type>carcass</detonation_type>
<detonation_radius>50</detonation_radius>
<detonation_duration>1</detonation_duration>
<detonation_speed>50</detonation_speed>
<detonation_damage>0.99</detonation_damage>
<particle_type>carcass_fragment</particle_type>
<particle_number>4</particle_number>
<explosion_particle_effect>explode_cone</explosion_particle_effect>
<distance_from_target>20</distance_from_target>
<error_margin>1</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJCcAAACPoY0kJwAAAI+hjSQnAAAAj6GNJCcAAACPoY0kJwAAAI+hjSQnAAAA
j6GNJCcAAACPoY0kJwAAAJDTqvEBAAAAj6GNJCcAAACPoY0kJwAAAI+hjSQnAAAA
j6GNJCcAAACPoY0kJwAAAGmTimEjAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{8CBAD8DB-813F-40EE-8409-FB3BF7EF1F3F}</s_GUID>
<s_Lineage>j6GNJCcAAABpk4phIwAAAJDTqvEiAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>carcass_24lb</key>
<detonator_type>fuse</detonator_type>
<detonation_type>carcass</detonation_type>
<detonation_radius>60</detonation_radius>
<detonation_duration>1</detonation_duration>
<detonation_speed>50</detonation_speed>
<detonation_damage>0.99</detonation_damage>
<particle_type>carcass_fragment</particle_type>
<particle_number>8</particle_number>
<explosion_particle_effect>explode_cone</explosion_particle_effect>
<distance_from_target>20</distance_from_target>
<error_margin>1</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJCUAAACPoY0kJQAAAI+hjSQlAAAAj6GNJCUAAACPoY0kJQAAAI+hjSQlAAAA
j6GNJCUAAACPoY0kJQAAAJDTqvEBAAAAj6GNJCUAAACPoY0kJQAAAI+hjSQlAAAA
j6GNJCUAAACPoY0kJQAAAGmTimEhAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{0954C6D2-5F0C-43C9-A100-EDB99DF9176E}</s_GUID>
<s_Lineage>j6GNJCUAAABpk4phIQAAAJDTqvEgAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>carcass_32lb</key>
<detonator_type>fuse</detonator_type>
<detonation_type>carcass</detonation_type>
<detonation_radius>70</detonation_radius>
<detonation_duration>1</detonation_duration>
<detonation_speed>50</detonation_speed>
<detonation_damage>0.99</detonation_damage>
<particle_type>carcass_fragment</particle_type>
<particle_number>5</particle_number>
<explosion_particle_effect>explode_cone</explosion_particle_effect>
<distance_from_target>20</distance_from_target>
<error_margin>1</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJB8AAACPoY0kHwAAAI+hjSQfAAAAj6GNJB8AAACPoY0kHwAAAI+hjSQfAAAA
j6GNJB8AAACPoY0kHwAAAJDTqvEBAAAAj6GNJB8AAACPoY0kHwAAAI+hjSQfAAAA
j6GNJB8AAACPoY0kHwAAAGmTimEbAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{0C3FA655-0D08-442C-96A1-DD4844E9F2A3}</s_GUID>
<s_Lineage>j6GNJB8AAABpk4phGwAAAJDTqvEaAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>carcass_4_mortar</key>
<detonator_type>fuse</detonator_type>
<detonation_type>carcass</detonation_type>
<detonation_radius>50</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>40</detonation_speed>
<detonation_damage>0.99</detonation_damage>
<particle_type>carcass_fragment</particle_type>
<particle_number>4</particle_number>
<explosion_particle_effect>explode_cone</explosion_particle_effect>
<distance_from_target>5</distance_from_target>
<error_margin>1</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJCEAAACPoY0kIQAAAI+hjSQhAAAAj6GNJCEAAACPoY0kIQAAAI+hjSQhAAAA
j6GNJCEAAACPoY0kIQAAAJDTqvEBAAAAj6GNJCEAAACPoY0kIQAAAI+hjSQhAAAA
j6GNJCEAAACPoY0kIQAAAGmTimEdAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{6C46331A-84DB-4FE6-B87B-242AF510D574}</s_GUID>
<s_Lineage>j6GNJCEAAABpk4phHQAAAJDTqvEcAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>carcass_8_mortar</key>
<detonator_type>fuse</detonator_type>
<detonation_type>carcass</detonation_type>
<detonation_radius>60</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>40</detonation_speed>
<detonation_damage>0.99</detonation_damage>
<particle_type>carcass_fragment</particle_type>
<particle_number>6</particle_number>
<explosion_particle_effect>explode_cone</explosion_particle_effect>
<distance_from_target>10</distance_from_target>
<error_margin>1</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJCAAAACPoY0kIAAAAI+hjSQgAAAAj6GNJCAAAACPoY0kIAAAAI+hjSQgAAAA
j6GNJCAAAACPoY0kIAAAAJDTqvEBAAAAj6GNJCAAAACPoY0kIAAAAI+hjSQgAAAA
j6GNJCAAAACPoY0kIAAAAGmTimEcAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{777B4343-96F6-452C-BF08-2E023E03D2B1}</s_GUID>
<s_Lineage>j6GNJCAAAABpk4phHAAAAJDTqvEbAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>grenade</key>
<detonator_type>fuse_grenade</detonator_type>
<detonation_type>shockwave</detonation_type>
<detonation_radius>0</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>0</detonation_speed>
<detonation_damage>0</detonation_damage>
<particle_type>grenade_fragment</particle_type>
<particle_number>3</particle_number>
<explosion_particle_effect>explode_grenade</explosion_particle_effect>
<distance_from_target>0</distance_from_target>
<error_margin>1</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJCcAAACPoY0kJwAAAI+hjSQnAAAAj6GNJCcAAACPoY0kJwAAAI+hjSQnAAAA
j6GNJCcAAACPoY0kJwAAAJDTqvESAAAAj6GNJCcAAACPoY0kJwAAAI+hjSQnAAAA
j6GNJCcAAACPoY0kJwAAAGmTimEjAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{E9823617-9075-4704-B813-6B9403147DC8}</s_GUID>
<s_Lineage>j6GNJCcAAABpk4phIwAAAJDTqvEiAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>grenade_improved</key>
<detonator_type>fuse_grenade</detonator_type>
<detonation_type>shockwave</detonation_type>
<detonation_radius>0</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>0</detonation_speed>
<detonation_damage>0</detonation_damage>
<particle_type>grenade_fragment</particle_type>
<particle_number>5</particle_number>
<explosion_particle_effect>explode_grenade</explosion_particle_effect>
<distance_from_target>0</distance_from_target>
<error_margin>0</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJAcAAACPoY0kBwAAAI+hjSQHAAAAj6GNJAcAAACPoY0kBwAAAI+hjSQHAAAA
j6GNJAcAAACPoY0kBwAAAJDTqvEBAAAAj6GNJAcAAACPoY0kBwAAAI+hjSQHAAAA
j6GNJAcAAACPoY0kBwAAAGmTimEDAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{C8F145D0-E6BB-4163-AA08-BE130443EB7F}</s_GUID>
<s_Lineage>j6GNJAcAAABpk4phAwAAAJDTqvECAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>mortar_4_ball</key>
<detonator_type>percussive</detonator_type>
<detonation_type>shockwave</detonation_type>
<detonation_radius>50</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>0</detonation_speed>
<detonation_damage>5</detonation_damage>
<particle_type>airgun</particle_type>
<particle_number>1</particle_number>
<distance_from_target>0</distance_from_target>
<error_margin>0</error_margin>
<non_lethal_detonation>1</non_lethal_detonation>
<s_ColLineage>j6GNJBcAAACPoY0kFwAAAI+hjSQXAAAAj6GNJBcAAACPoY0kFwAAAI+hjSQXAAAA
j6GNJBcAAACPoY0kFwAAAJDTqvEBAAAAj6GNJBcAAACPoY0kFwAAAI+hjSQXAAAA
j6GNJBcAAACPoY0kFwAAAGmTimETAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{F152B1A8-1F25-4514-99C3-30C218804EA3}</s_GUID>
<s_Lineage>j6GNJBcAAABpk4phEwAAAJDTqvEOAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>mortar_4_shell</key>
<detonator_type>fuse</detonator_type>
<detonation_type>shockwave</detonation_type>
<detonation_radius>4</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>10</detonation_speed>
<detonation_damage>15</detonation_damage>
<particle_type>shell_fragment</particle_type>
<particle_number>18</particle_number>
<explosion_particle_effect>explode_frag_med</explosion_particle_effect>
<distance_from_target>10</distance_from_target>
<error_margin>0</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJBcAAACPoY0kFwAAAI+hjSQXAAAAj6GNJBcAAACPoY0kFwAAAI+hjSQXAAAA
j6GNJBcAAACPoY0kFwAAAJDTqvEFAAAAj6GNJBcAAACPoY0kFwAAAI+hjSQXAAAA
j6GNJBcAAACPoY0kFwAAAGmTimETAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{F48560D3-56CB-4EFF-8EB7-9AB385B99E6C}</s_GUID>
<s_Lineage>j6GNJBcAAABpk4phEwAAAJDTqvERAAAAAAAAAAAAAAA=
</s_Lineage>
<project_specific>0</project_specific>
</projectiles_explosions>
<projectiles_explosions>
<key>mortar_8_shell</key>
<detonator_type>fuse</detonator_type>
<detonation_type>shockwave</detonation_type>
<detonation_radius>5</detonation_radius>
<detonation_duration>0</detonation_duration>
<detonation_speed>10</detonation_speed>
<detonation_damage>25</detonation_damage>
<particle_type>shell_fragment</particle_type>
<particle_number>32</particle_number>
<explosion_particle_effect>explode_frag_lrg</explosion_particle_effect>
<distance_from_target>15</distance_from_target>
<error_margin>0</error_margin>
<non_lethal_detonation>0</non_lethal_detonation>
<s_ColLineage>j6GNJBkAAACPoY0kGQAAAI+hjSQZAAAAj6GNJBkAAACPoY0kGQAAAI+hjSQZAAAA
j6GNJBkAAACPoY0kGQAAAJDTqvEFAAAAj6GNJBkAAACPoY0kGQAAAI+hjSQZAAAA
j6GNJBkAAACPoY0kGQAAAGmTimEVAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
