=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/start_pos_character_ancillaries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="start_pos_character_ancillaries" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="start_pos_character_ancillaries">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="id" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="character_id" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="ancillary" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_ColLineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Generation" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="s_GUID" minOccurs="0" od:jetType="replicationid" od:sqlSType="uniqueidentifier" od:autoUnique="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="38"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="s_Lineage" minOccurs="0" od:jetType="oleobject" od:sqlSType="image">
<xsd:simpleType>
<xsd:restriction base="xsd:base64Binary">
<xsd:maxLength value="1476395008"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Frodo45127/total_war_ak_files_pre_shogun_2/napoleon/start_pos_character_ancillaries.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="start_pos_character_ancillaries.xsd" generated="2009-08-26T15:24:24">
<start_pos_character_ancillaries>
<id>-1916727510</id>
<character_id>1241788327</character_id>
<ancillary>Ancillary_Army_ADC</ancillary>
<s_ColLineage>sZqs6wEAAACxmqzrAgAAALGarOsDAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{F7089518-27A2-4563-BA6D-241BE1979611}</s_GUID>
<s_Lineage>sZqs6wMAAAAAAAAAAAAAAA==
</s_Lineage>
</start_pos_character_ancillaries>
<start_pos_character_ancillaries>
<id>-1028684773</id>
<character_id>1248795041</character_id>
<ancillary>Ancillary_Army_ADC</ancillary>
<s_ColLineage>W4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{7F65DABC-F967-4AB1-BA81-7CDDCD4D9A36}</s_GUID>
<s_Lineage>W4e7tQIAAAAAAAAAAAAAAA==
</s_Lineage>
</start_pos_character_ancillaries>
<start_pos_character_ancillaries>
<id>-917382624</id>
<character_id>2023806109</character_id>
<ancillary>Ancillary_Army_ADC</ancillary>
<s_ColLineage>W4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{52AD5AAD-0818-479F-841D-C24F39CF9F30}</s_GUID>
<s_Lineage>W4e7tQIAAAAAAAAAAAAAAA==
</s_Lineage>
</start_pos_character_ancillaries>
<start_pos_character_ancillaries>
<id>322286117</id>
<character_id>1249486047</character_id>
<ancillary>Ancillary_Government_Comptroller</ancillary>
<s_ColLineage>W4e7tQEAAABbh7u1AgAAAFuHu7UCAAAA
</s_ColLineage>
<s_Generation>0</s_Generation>
<s_GUID>{B80F0A40-2C03-4954-8A06-352E1D63A7B1}</s_GUID>
<s_Lineage>W4e7tQIAAAAAAAAAAAAAAA==
</s_Lineage>
</start_pos_character_ancillaries>
</dataroot>
